### ISSUE TITLE
How do I install this package as of 0.12.0 ?

### ISSUE THREAD

**Issue by zenshidev** [joadnacer/jdz_allocator#3]
As per README, there is a:
`exe.addModule("jdz_allocator", jdz_allocator.module("jdz_allocator"));`

but in released 0.12.0, `exe.addModule()` function no longer exists, and I cant find whats the replacement.
Have you tried installing it since 0.12.0 ?

**Comment by zenshidev** [comment]
Aaaaaaaand soon after making this issue I finally found it:
```
    const jdz_dep = b.dependency("jdz_allocator", .{
        .target = target,
        .optimize = optimize,
    });

    const exe = b.addExecutable(.{
        .name = "zapts",
        .root_source_file = .{ .path = "src/main.zig" },
        .target = target,
        .optimize = optimize,
    });
    exe.root_module.addImport("jdz_allocator", jdz_dep.module("jdz_allocator"));
    b.installArtifact(exe);
```

**Comment by joadnacer** [comment]
Thanks for raising the issue, have now updated the README.
