### ISSUE TITLE
how to install this package in 0.13.0? (and above)

### ISSUE THREAD

**Issue by keizertje** [joadnacer/jdz_allocator#8]
The readme states that the current master is written for zig 0.13.0, however, when I follow the instructions, and execute `zig build`, an error tells me that there is made use of the `.path` field (in `Build.LazyPath`), which is deprecated in zig 0.13.0. I think the issue is that the link in the readme is an archive that has this use of the `.path` field. could you update the link?

**Comment by joadnacer** [comment]
Fixed the url + hash in the readme, should work now
